// Package store wraps the Postgres data layer.
//
// Queries are hand-written against pgx rather than generated by sqlc to
// keep the dependency surface small; the trade-off is that each query has
// to spell out its column list and scan targets. The query bodies live in
// queries.go; this file holds the connection plumbing and types.
package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Doc mirrors a row in the docs table.
type Doc struct {
	ID          uuid.UUID
	Source      string
	Title       string
	Body        string
	ContentHash string
	CreatedAt   time.Time
	// DeletedAt is non-nil when the doc has been soft-deleted via
	// DELETE /v1/docs/{id}. Search paths skip these rows.
	DeletedAt *time.Time
}

// Chunk mirrors doc_chunks. Embedding is stored as a []float32 in Go and
// rendered to the pgvector text format on the way in.
type Chunk struct {
	ID         uuid.UUID
	DocID      uuid.UUID
	ChunkIndex int
	Text       string
	Embedding  []float32
}

// Hit is one row from a hybrid search.
type Hit struct {
	DocID      uuid.UUID
	ChunkID    uuid.UUID
	ChunkIndex int
	Snippet    string
	Score      float64
}

// Store is the entry point for everything the API and indexer need.
type Store struct {
	Pool *pgxpool.Pool
}

// Open dials Postgres and returns a Store. callers are responsible for
// invoking Close() when done.
func Open(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("store: parse dsn: %w", err)
	}
	cfg.MaxConns = 16
	cfg.MinConns = 2
	cfg.HealthCheckPeriod = 30 * time.Second
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("store: dial: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &Store{Pool: pool}, nil
}

// Close releases the underlying pool.
func (s *Store) Close() {
	if s.Pool != nil {
		s.Pool.Close()
	}
}

// ErrNotFound is returned when a single-row lookup misses.
var ErrNotFound = errors.New("not found")

// translateNoRows turns pgx.ErrNoRows into our exported sentinel.
func translateNoRows(err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrNotFound
	}
	return err
}
